<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-05-24 10:58
=======
# Generated by Django 5.0.6 on 2024-05-28 14:55
>>>>>>> 6-crud-samochodw

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
