# Generated by Django 5.0.6 on 2024-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=7)),
                ('technical_review_date', models.DateField(max_length=9)),
                ('insurance_date', models.DateField(max_length=10)),
            ],
        ),
    ]
